In [2]:
import pandas as pd
import numpy as np

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:
df = pd.read_csv( "/content/drive/MyDrive/4.0_Fourth_Year/CIV498/VisionZero/!Resources/Data/tmcs_2010_2019.csv" ) 
df.head()

   count_id count_date  location_id  ... sx_other  ex_other  wx_other
0     25081  1/12/2010        32187  ...      0.0       0.0       0.0
1     25081  1/12/2010        32187  ...      0.0       0.0       0.0
2     25081  1/12/2010        32187  ...      0.0       0.0       0.0
3     25081  1/12/2010        32187  ...      0.0       0.0       0.0
4     25081  1/12/2010        32187  ...      0.0       0.0       0.0

[5 rows x 59 columns]

Our goal is to aggregate these counts by day and sum the daily traffic at each count. Then preferably take only the most recent count for each location.

In [17]:
#1.0 create a day column 
df['date'] = df['time_start'].astype(str).str[0:10]

#2.0 sum all through movements, grouped by mode 
#Through movements 
df["cars_t"] = df["sb_cars_t"] + df["nb_cars_t"] + df["eb_cars_t"] + df["wb_cars_t"]
df["truck_t"] = df["sb_truck_t"] + df["nb_truck_t"] + df["eb_truck_t"] + df["wb_truck_t"] 
df["bus_t"] = df["sb_bus_t"] + df["nb_bus_t"] + df["eb_bus_t"] + df["wb_bus_t"]

#Left turns 
df["cars_l"] = df["sb_cars_l"] + df["nb_cars_l"] + df["eb_cars_l"] + df["wb_cars_l"]
df["truck_l"] = df["sb_truck_l"] + df["nb_truck_l"] + df["eb_truck_l"] + df["wb_truck_l"]
df["bus_l"] = df["sb_bus_l"] + df["nb_bus_l"] + df["eb_bus_l"] + df["wb_bus_l"]

#Right turns
df["cars_r"] = df["sb_cars_r"] + df["nb_cars_r"] + df["eb_cars_r"] + df["wb_cars_r"]
df["truck_r"] = df["sb_truck_r"] + df["nb_truck_r"] + df["eb_truck_r"] + df["wb_truck_r"]
df["bus_r"] = df["sb_bus_r"] + df["nb_bus_r"] + df["eb_bus_r"] + df["wb_bus_r"]

#Peds
df["sum_peds"] = df["nx_peds"] + df["sx_peds"] + df["ex_peds"] + df["wx_peds"]

In [ ]:
#3.0 copy for paranoia's sake
df2 = df.copy( deep=True )

In [23]:
counts_grouped = df2.groupby( ["lat", "lng", "date"])["cars_t", "truck_t", "bus_t", "cars_l", "truck_l", "bus_l", "cars_r", "truck_r", "bus_r", "sum_peds"].apply( lambda x: x.astype( float ).sum() )

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

In [26]:
counts_grouped.to_csv( "/content/drive/MyDrive/4.0_Fourth_Year/CIV498/VisionZero/Google Colab/Data_Cleaning/counts_grouped.csv" )

Cleaning speed counts from vision zero github

In [3]:
speeds = pd.read_csv( "/content/drive/MyDrive/4.0_Fourth_Year/CIV498/VisionZero/!Resources/Data/speed_counts_summary.csv" )

   centreline_id  direction  ... speed_kph_85 speed_kph_95
0            117  Eastbound  ...        44.63        48.80
1            117  Eastbound  ...        44.28        48.62
2            117  Eastbound  ...        44.54        48.66
3            117  Eastbound  ...        44.03        48.67
4            117  Eastbound  ...        39.21        43.19

[5 rows x 7 columns]

In [10]:
g = speeds.groupby(["centreline_id", "direction", "location"])
g["dt"].rank( method ='min')

DataError: ignored